\documentclass{beamer}\usepackage[]{graphicx}\usepackage[]{color}
%% maxwidth is the original width if it is less than linewidth
%% otherwise use linewidth (to make sure the graphics do not exceed the margin)
\makeatletter
\def\maxwidth{ %
  \ifdim\Gin@nat@width>\linewidth
    \linewidth
  \else
    \Gin@nat@width
  \fi
}
\makeatother

\definecolor{fgcolor}{rgb}{1, 0.894, 0.769}
\newcommand{\hlnum}[1]{\textcolor[rgb]{0.824,0.412,0.118}{#1}}%
\newcommand{\hlstr}[1]{\textcolor[rgb]{1,0.894,0.71}{#1}}%
\newcommand{\hlcom}[1]{\textcolor[rgb]{0.824,0.706,0.549}{#1}}%
\newcommand{\hlopt}[1]{\textcolor[rgb]{1,0.894,0.769}{#1}}%
\newcommand{\hlstd}[1]{\textcolor[rgb]{1,0.894,0.769}{#1}}%
\newcommand{\hlkwa}[1]{\textcolor[rgb]{0.941,0.902,0.549}{#1}}%
\newcommand{\hlkwb}[1]{\textcolor[rgb]{0.804,0.776,0.451}{#1}}%
\newcommand{\hlkwc}[1]{\textcolor[rgb]{0.78,0.941,0.545}{#1}}%
\newcommand{\hlkwd}[1]{\textcolor[rgb]{1,0.78,0.769}{#1}}%
\let\hlipl\hlkwb

\usepackage{framed}
\makeatletter
\newenvironment{kframe}{%
 \def\at@end@of@kframe{}%
 \ifinner\ifhmode%
  \def\at@end@of@kframe{\end{minipage}}%
  \begin{minipage}{\columnwidth}%
 \fi\fi%
 \def\FrameCommand##1{\hskip\@totalleftmargin \hskip-\fboxsep
 \colorbox{shadecolor}{##1}\hskip-\fboxsep
     % There is no \\@totalrightmargin, so:
     \hskip-\linewidth \hskip-\@totalleftmargin \hskip\columnwidth}%
 \MakeFramed {\advance\hsize-\width
   \@totalleftmargin\z@ \linewidth\hsize
   \@setminipage}}%
 {\par\unskip\endMakeFramed%
 \at@end@of@kframe}
\makeatother

\definecolor{shadecolor}{rgb}{.97, .97, .97}
\definecolor{messagecolor}{rgb}{0, 0, 0}
\definecolor{warningcolor}{rgb}{1, 0, 1}
\definecolor{errorcolor}{rgb}{1, 0, 0}
\newenvironment{knitrout}{}{} % an empty environment to be redefined in TeX

\usepackage{alltt}
\usepackage{../371g-slides}
\usepackage{preview}
\title{Time Series: Autocorrelation}
\subtitle{Lecture 18}
\author{STA 371G}
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\begin{document}
  
  

  \frame{\maketitle}

  % Show outline at beginning of each section
  \AtBeginSection[]{ 
    \begin{frame}<beamer>
      \tableofcontents[currentsection]
    \end{frame}
  }

  %%%%%%% Slides start here %%%%%%%

  \begin{darkframes}
    

    \begin{frame}{Predicting beer production over time}
    \begin{center}
        \includegraphics[width=2.8in]{beer} \\
      \end{center} 
      Goal: Predict beer production in the US (in millions of gallons)
      \lc
      \end{frame} 
\begin{frame}[fragile]{An autoregressive model for beer production}
    If we believe last month's beer figures are a good prediction for next month's beer figures, we might choose an AR(1) model:
    
    $$y_t = \beta_0 + \beta_1 y_{t-1} + \epsilon_t$$
    
    This means that the next month's beer figures depend only on the current month's beer figures, plus random noise.
    
   \bigskip
   
   Let's look at whether this seems a reasonable assumption
\end{frame}
\begin{frame}[fragile]%{An autoregressive model for beer production}
    \fontsize{8}{8}\selectfont
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.137, 0.137, 0.137}\begin{kframe}
\begin{alltt}
\hlcom{# Convert the data into a time series object    }
\hlstd{beer} \hlkwb{<-} \hlkwd{ts}\hlstd{(beer.df}\hlopt{$}\hlstd{beer,} \hlkwc{start}\hlstd{=}\hlkwd{c}\hlstd{(}\hlnum{1970}\hlstd{,}\hlnum{7}\hlstd{),} \hlkwc{frequency}\hlstd{=}\hlnum{12}\hlstd{)}
\hlcom{# Create a lag-1 version   }
\hlstd{beerL1} \hlkwb{<-} \hlkwd{lag}\hlstd{(beer,} \hlkwc{k}\hlstd{=}\hlopt{-}\hlnum{1}\hlstd{)}
\hlcom{#combine them in a data frame}
\hlstd{beer_all} \hlkwb{<-} \hlkwd{cbind}\hlstd{(}\hlkwc{beer}\hlstd{=beer,}\hlkwc{beerL1}\hlstd{=beerL1)}
\hlcom{# Frequency: # of data points per year}
\hlkwd{plot}\hlstd{(beer}\hlopt{~}\hlstd{beerL1,}\hlkwc{data}\hlstd{=beer_all,}\hlkwc{xlab} \hlstd{=} \hlstr{"last month\textbackslash{}'s beer production"}\hlstd{,}\hlkwc{ylab}\hlstd{=}\hlstr{"this month\textbackslash{}'s beer production"}\hlstd{,}\hlkwc{pch}\hlstd{=}\hlnum{19}\hlstd{)}
\end{alltt}
\end{kframe}
\input{/tmp/figures/unnamed-chunk-2-1.tex}

\end{knitrout}
      \lc
\end{frame}

\begin{frame}[fragile]%{Linear regression model}
      \fontsize{8}{8}\selectfont
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.137, 0.137, 0.137}\begin{kframe}
\begin{alltt}
\hlstd{model} \hlkwb{<-} \hlkwd{lm}\hlstd{(beer} \hlopt{~} \hlstd{beerL1,} \hlkwc{data}\hlstd{=beer_all)}
\hlkwd{summary}\hlstd{(model)}
\end{alltt}
\begin{verbatim}

Call:
lm(formula = beer ~ beerL1, data = beer_all)

Residuals:
    Min      1Q  Median      3Q     Max 
-2.6018 -0.8428 -0.1902  0.8539  4.5109 

Coefficients:
            Estimate Std. Error t value Pr(>|t|)    
(Intercept)  2.25720    0.80557   2.802  0.00618 ** 
beerL1       0.82136    0.06417  12.800  < 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.183 on 93 degrees of freedom
  (2 observations deleted due to missingness)
Multiple R-squared:  0.6379,	Adjusted R-squared:  0.634 
F-statistic: 163.8 on 1 and 93 DF,  p-value: < 2.2e-16
\end{verbatim}
\end{kframe}
\end{knitrout}
      
      Last month's beer production is statistically significant. The $R^2$ is good, but not amazing... perhaps we can do better!
\end{frame}

\begin{frame}[fragile]%{Linear regression model}
Hmmm... there seems to be more of a pattern here than in the oil price data from last week!
      \fontsize{9}{9}\selectfont
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.137, 0.137, 0.137}\begin{kframe}
\begin{alltt}
\hlkwd{plot}\hlstd{(beer)}
\end{alltt}
\end{kframe}
\input{/tmp/figures/unnamed-chunk-4-1.tex}

\end{knitrout}
      
\end{frame}
    \begin{frame}
\frametitle{Types of temporal variation}
There are several types of temporal variation we might want to predict!

\bigskip

Cyclic variation is \emph{unpredictable} up and down movement, of the sort we saw last week. 
\begin{itemize}
\item Length of cycle may vary
\item Often caused by multiple interacting factors.
\item Example: Stock prices vary due to recessions, depressions and recoveries.
\item Example: Sales may be affected by fashions.
\end{itemize}

\pause
If we don't know those factors, often the best we can do is predict based on the last time point... i.e.\ an autoregressive model.

\end{frame}
\begin{frame}
\frametitle{Trend}
A \alert{trend} is a persistent, overall, upwards or downwards pattern in the data.
\begin{itemize}
\item Example: Effects due to population growth (e.g. demand on health services).
\item Example: ``Moore's Law'' -- processor speeds double every two years.
\item Could be linear or non-linear -- the trend may continue at a constant rate, or accelerate, or level off.
\end{itemize}
We definitely saw a trend in the beer production numbers!
\end{frame}
    
\begin{frame}
\frametitle{Seasonal}
\begin{itemize}
\item \alert{Seasonal variation} is a regular pattern of up and down fluctuation.
\item The length of the cycle is the same (e.g. yearly, monthly)
\item Caused by effects such as weather, holidays.
\item It is predictable.
\item Example: Toy sales increase in December.
\item Example: Ice cream sales affected by the weather.
\end{itemize}
There was clear seasonality in the beer production numbers!
\lc
\end{frame}


\begin{frame}[fragile]{Modeling a trend}
    \fontsize{8}{8}\selectfont
      Let's first deal with the upward trend. We can try predicting production from time using a simple linear regression:
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.137, 0.137, 0.137}\begin{kframe}
\begin{alltt}
\hlkwd{summary}\hlstd{(}\hlkwd{lm}\hlstd{(beer} \hlopt{~} \hlstd{month_count,} \hlkwc{data}\hlstd{=beer.df))}
\end{alltt}
\begin{verbatim}

Call:
lm(formula = beer ~ month_count, data = beer.df)

Residuals:
     Min       1Q   Median       3Q      Max 
-2.87729 -1.48470  0.00505  1.31704  2.80344 

Coefficients:
             Estimate Std. Error t value Pr(>|t|)    
(Intercept) 10.576746   0.334920  31.580  < 2e-16 ***
month_count  0.038784   0.005996   6.468 4.42e-09 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.628 on 94 degrees of freedom
Multiple R-squared:  0.308,	Adjusted R-squared:  0.3006 
F-statistic: 41.84 on 1 and 94 DF,  p-value: 4.415e-09
\end{verbatim}
\end{kframe}
\end{knitrout}
      \pause
      Month is a significant predictor! But the $R^2$ is lower than our AR(1) model, so we need to do better.
\end{frame}   
    

\begin{frame}{Seasonal variation}
How can we deal with the seasonal effect?
\pause
\bigskip

The simplest solution is to treat month as a categorical variable!
\begin{itemize}
\item This means that we assume there is some commonality between September 1970, September 1971, September 1972...
\item More general, we might want to treat quarters or days of the weeks as categorical variables.
\end{itemize}
\end{frame}

\begin{frame}[fragile]%{Adding seasonal dummies}
    \fontsize{7}{7}\selectfont
      
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.137, 0.137, 0.137}\begin{kframe}
\begin{verbatim}

Call:
lm(formula = beer ~ month_count + month, data = beer.df)

Residuals:
     Min       1Q   Median       3Q      Max 
-2.23574 -0.30407 -0.01724  0.40160  1.65361 

Coefficients:
                Estimate Std. Error t value Pr(>|t|)    
(Intercept)    11.462493   0.255140  44.926  < 2e-16 ***
month_count     0.037887   0.002351  16.114  < 2e-16 ***
monthAugust     0.400097   0.317257   1.261 0.210801    
monthDecember  -2.752326   0.316839  -8.687 2.76e-13 ***
monthFebruary  -2.686726   0.316734  -8.483 7.08e-13 ***
monthJanuary   -2.159214   0.316778  -6.816 1.39e-09 ***
monthJuly       1.164859   0.317405   3.670 0.000428 ***
monthJune       1.227101   0.316734   3.874 0.000213 ***
monthMarch     -0.440613   0.316708  -1.391 0.167874    
monthMay        0.642738   0.316708   2.029 0.045618 *  
monthNovember  -3.026064   0.316917  -9.548 5.23e-15 ***
monthOctober   -1.544927   0.317013  -4.873 5.20e-06 ***
monthSeptember -0.932040   0.317127  -2.939 0.004263 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.6334 on 83 degrees of freedom
Multiple R-squared:  0.9075,	Adjusted R-squared:  0.8941 
F-statistic: 67.86 on 12 and 83 DF,  p-value: < 2.2e-16
\end{verbatim}
\end{kframe}
\end{knitrout}
      \lc
\end{frame}
\begin{frame}[fragile]
\begin{itemize}
\item Now that we've modeled seasonality, we've got an $R^2$ of 0.9075 and an adjusted $R^2$ of 0.8941... pretty good!
\item We've modeled the trend and the seasonality...
\pause
\item ... maybe there's also a cyclic effect! Let's take a look at the residuals.
\end{itemize}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.137, 0.137, 0.137}\begin{kframe}
\begin{alltt}
      \hlcom{# Convert the residuals into a time series object    }
      \hlstd{beer_res} \hlkwb{<-} \hlkwd{ts}\hlstd{(model}\hlopt{$}\hlstd{residuals,} \hlkwc{start}\hlstd{=}\hlkwd{c}\hlstd{(}\hlnum{1970}\hlstd{,}\hlnum{7}\hlstd{),} \hlkwc{frequency}\hlstd{=}\hlnum{12}\hlstd{)}
      \hlkwd{plot}\hlstd{(beer_res)}
\end{alltt}
\end{kframe}
\input{/tmp/figures/unnamed-chunk-7-1.tex}

\end{knitrout}
\end{frame}

\begin{frame}[fragile]
Let's try running an autoregressive model on the residuals
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.137, 0.137, 0.137}\begin{kframe}
\begin{alltt}
\hlstd{beer_res_L1} \hlkwb{<-} \hlkwd{lag}\hlstd{(beer_res,} \hlkwc{k}\hlstd{=}\hlopt{-}\hlnum{1}\hlstd{)}
\hlstd{res_all} \hlkwb{<-} \hlkwd{cbind}\hlstd{(}\hlkwc{beer_res} \hlstd{= beer_res,}
                 \hlkwc{beer_res_L1} \hlstd{= beer_res_L1)}
\hlstd{model} \hlkwb{<-} \hlkwd{lm}\hlstd{(beer_res}\hlopt{~}\hlstd{beer_res_L1,}\hlkwc{data}\hlstd{=res_all)}
\end{alltt}
\end{kframe}
\end{knitrout}
\end{frame}
\begin{frame}[fragile]
    \fontsize{9}{9}\selectfont
      
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.137, 0.137, 0.137}\begin{kframe}
\begin{verbatim}

Call:
lm(formula = beer_res ~ beer_res_L1, data = res_all)

Residuals:
     Min       1Q   Median       3Q      Max 
-2.25571 -0.34325 -0.00875  0.35091  1.86982 

Coefficients:
             Estimate Std. Error t value Pr(>|t|)   
(Intercept) -0.002829   0.058897  -0.048   0.9618   
beer_res_L1  0.273770   0.099983   2.738   0.0074 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.574 on 93 degrees of freedom
  (2 observations deleted due to missingness)
Multiple R-squared:  0.0746,	Adjusted R-squared:  0.06465 
F-statistic: 7.498 on 1 and 93 DF,  p-value: 0.007404
\end{verbatim}
\end{kframe}
\end{knitrout}
Statistically significant... but not really practically significant
\end{frame}  

\begin{frame}[fragile]
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.137, 0.137, 0.137}
\input{/tmp/figures/unnamed-chunk-10-1.tex}

\end{knitrout}
      Autocorrelation function agrees... fairly low autocorrelation at lag one.
      \note{Three bonus LC questions}
\end{frame}
  \end{darkframes}
\end{document}
